Fix Travis build error
Error was :
Looking for dependencies...
Project does not have dependencies
Error: Nothing to build. Please put your source code files to '/home/travis/build/michelepagot/autopresepio/src' folder
========================== [ERROR] Took 0.58 seconds ==========================